import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { CitiesNamesContextProvider } from "./context/citiesNamesContext";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "wfc-next-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <CitiesNamesContextProvider>{children}</CitiesNamesContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
